// Supabase Configuration
const SUPABASE_URL = 'https://pjtuisyvpvoswmcgxsfs.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdHVpc3l2cHZvc3dtY2d4c2ZzIiwicm9zZSI6ImFub24iLCJpYXQiOjE3NjE1Mzg1MDUsImV4cCI6MjA3NzExNDUwNX0.Zj8WxKjj8d2tq2c5ATxN5RtvuIK5sLXPzM2ZC00vIzY';

// Initialize Supabase client
let supabaseClient = null;

function getSupabaseClient() {
    if (supabaseClient) return supabaseClient;
    
    if (!window.supabase?.createClient) {
        throw new Error('Supabase JS library not loaded');
    }
    
    supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: { 
            persistSession: true, 
            autoRefreshToken: true,
            detectSessionInUrl: false
        }
    });
    
    return supabaseClient;
}

// ========================================
// PARTICIPANT API FUNCTIONS
// ========================================

/**
 * Register a new participant
 * Schema: id, name, email, username, total_votes, total_amount, 
 *         current_stage, achievement_badges, created_at, updated_at, user_code
 * Triggers: assign_user_code, auto_generate_user_data, create_referral_link
 */
async function registerParticipant(name, email, username) {
    const client = getSupabaseClient();
    
    // Normalize inputs
    const normalizedEmail = email.trim().toLowerCase();
    const normalizedUsername = username.trim().toLowerCase();
    
    // Validate username format
    if (!/^[a-z0-9_]+$/.test(normalizedUsername)) {
        throw new Error('Username can only contain lowercase letters, numbers, and underscores.');
    }
    
    if (normalizedUsername.length < 3) {
        throw new Error('Username must be at least 3 characters long.');
    }
    
    // Check existing email (unique constraint: participants_email_key)
    const { data: existingEmail, error: emailErr } = await client
        .from('participants')
        .select('id')
        .eq('email', normalizedEmail)
        .limit(1);
    
    if (emailErr) throw new Error(`Database error: ${emailErr.message}`);
    if (existingEmail?.length > 0) {
        throw new Error('An account with this email already exists.');
    }
    
    // Check existing username (unique constraint: participants_username_key)
    const { data: existingUsername, error: usernameErr } = await client
        .from('participants')
        .select('id')
        .eq('username', normalizedUsername)
        .limit(1);
    
    if (usernameErr) throw new Error(`Database error: ${usernameErr.message}`);
    if (existingUsername?.length > 0) {
        throw new Error('This username is already taken.');
    }
    
    // Insert participant
    // Note: user_code is auto-generated by trigger_assign_user_code
    // Note: referral_link is auto-created by trigger_create_referral_link
    const { data: participant, error: insertErr } = await client
        .from('participants')
        .insert({ 
            name: name.trim(), 
            email: normalizedEmail, 
            username: normalizedUsername 
        })
        .select(`
            id, 
            name, 
            email, 
            username, 
            user_code,
            total_votes, 
            total_amount,
            current_stage, 
            achievement_badges,
            created_at,
            updated_at
        `)
        .single();
    
    if (insertErr) {
        // Handle unique constraint violations
        if (insertErr.code === '23505') {
            if (insertErr.message.includes('email')) {
                throw new Error('An account with this email already exists.');
            }
            if (insertErr.message.includes('username')) {
                throw new Error('This username is already taken.');
            }
            if (insertErr.message.includes('user_code')) {
                throw new Error('Registration failed. Please try again.');
            }
        }
        throw new Error(`Failed to create account: ${insertErr.message}`);
    }
    
    // Wait for trigger to create referral link
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Get referral link (created by trigger_create_referral_link)
    const { data: referralLink } = await client
        .from('referral_links')
        .select('user_vote_link')
        .eq('participant_id', participant.id)
        .single();
    
    return {
        ...participant,
        voteLink: referralLink?.user_vote_link || `https://www.flymaddcreative.online/vote.html?user=${normalizedUsername}`
    };
}

/**
 * Get participant by username
 */
async function getParticipantByUsername(username) {
    const client = getSupabaseClient();
    
    const { data, error } = await client
        .from('participants')
        .select(`
            id, 
            name, 
            email, 
            username, 
            user_code,
            total_votes, 
            total_amount,
            current_stage, 
            achievement_badges,
            created_at
        `)
        .eq('username', username.toLowerCase())
        .single();
    
    if (error) return null;
    return data;
}

/**
 * Get participant by user_code
 */
async function getParticipantByUserCode(userCode) {
    const client = getSupabaseClient();
    
    const { data, error } = await client
        .from('participants')
        .select(`
            id, 
            name, 
            email, 
            username, 
            user_code,
            total_votes, 
            total_amount,
            current_stage, 
            achievement_badges,
            created_at
        `)
        .eq('user_code', userCode.toUpperCase())
        .single();
    
    if (error) return null;
    return data;
}

/**
 * Get leaderboard (top participants by votes)
 */
async function getLeaderboard(limit = 50) {
    const client = getSupabaseClient();
    
    const { data, error } = await client
        .from('participants')
        .select(`
            id, 
            name, 
            username, 
            user_code,
            total_votes, 
            total_amount,
            current_stage, 
            achievement_badges,
            created_at
        `)
        .order('total_votes', { ascending: false })
        .limit(limit);
    
    if (error) throw new Error(error.message);
    return data || [];
}

/**
 * Search participants by username or user_code
 */
async function searchParticipants(query) {
    const client = getSupabaseClient();
    const searchTerm = query.trim();
    
    if (!searchTerm) return [];
    
    const { data, error } = await client
        .from('participants')
        .select(`
            id, 
            name, 
            username, 
            user_code,
            total_votes, 
            current_stage
        `)
        .or(`username.ilike.%${searchTerm}%,user_code.ilike.%${searchTerm}%,name.ilike.%${searchTerm}%`)
        .order('total_votes', { ascending: false })
        .limit(20);
    
    if (error) throw new Error(error.message);
    return data || [];
}

/**
 * Test database connection
 */
async function testConnection() {
    const client = getSupabaseClient();
    const { data, error } = await client
        .from('participants')
        .select('id, username, user_code')
        .limit(3);
    
    return { success: !error, data, error };
}

// ========================================
// EXPORT FOR GLOBAL ACCESS
// ========================================
window.SupabaseAPI = {
    getClient: getSupabaseClient,
    registerParticipant,
    getParticipantByUsername,
    getParticipantByUserCode,
    getLeaderboard,
    searchParticipants,
    testConnection
};

console.log('✅ Supabase API loaded');
